# Usa una imagen base de Node.js para construir la app
FROM node:16 AS build

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos del proyecto
COPY ./angular_app/package.json ./angular_app/package-lock.json /app/

# Instala las dependencias de Angular
RUN npm install

# Copia el resto de los archivos
COPY ./angular_app /app

# Construye la aplicación Angular para producción
RUN npm run build --prod

# Usa Nginx para servir la app Angular
FROM nginx:alpine

# Copia los archivos generados por Angular en la carpeta de Nginx
COPY --from=build /app/dist/ /usr/share/nginx/html

# Expone el puerto 80
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
