
services:
  backend_api:
    build:
      context: ./backend_api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - proyecto-net
    depends_on:
      - mongo

  angular_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - proyecto-net
    depends_on:
      - backend_api

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - proyecto-net

networks:
  proyecto-net:
    driver: bridge
